// ========== Массив машин ==========
const cars = [  { 
  name: "Buick Electra 225",
  brand: "Buick", 
  number: "70.000", 
  liter: "7.0", 
  image: "https://i.postimg.cc/PN0yGv62/IMG-20250621-141219.jpg", 
  details:"The Buick Electra 225 was a full-size luxury car produced by Buick from 1959 to 1990. Known for its length, comfort, and smooth V8 engine, it became a symbol of American luxury in the 1960s and 70s. The 225 refers to the car's overall length of 225 inches — nearly 5.7 meters!", 

},

  { name: "Chevrolet Task Force",  
    brand: "Chevrolet",
    liter: "3.9", 
    number: "598.000",
    image: "https://i.postimg.cc/p9748wsJ/482b4006-c4ef-4c63-8e9d-45ae40223029-2.png", 
    details:"The Chevrolet Task Force was a series of pickup trucks produced from 1955 to 1959. It followed the Advance Design series and introduced more modern styling and features for its time.", 
    year: "1941",
  horsepower: "95",
  maxspeed: "100-105 km/hour",
  fabriek: "Flint, USA",
  unique: "the age of car",
  datum: "22-08-2024",
  },
    
  { name: "Cadillac Series 62 Sedan", 
    brand: "Cadillac",
    liter: "5.4",
    number: "74.374", 
    image: "https://i.postimg.cc/qgCh82vs/d0572b49-2e28-4ad9-bf4a-04f00e649f1a.png", 
    details:"The Cadillac Series 62 Sedan was a luxury automobile produced by Cadillac from 1940 to 1964. It became one of the brand’s most iconic models, known for its chrome-heavy style, powerful V8 engines, and smooth ride." },
  
    { name: "Mercedes-Benz 190 SL", 
      brand: "Mercedes-Benz",
      liter: "5,2",
      number: "25.881", 
      image: "https://i.postimg.cc/gXGwN1yk/f7f930e0-098b-4f65-8288-1db22649e48c.png", 
      details:"The Mercedes-Benz 190 SL is a luxurious roadster produced between 1955 and 1963. It was developed as a more affordable alternative to the famous 300 SL." },
  
      { name: "Chevrolet Pickup (Master Series)", 
        number: "40-50 million",
        liter: "5.3", 
        brand: "Chevrolet",
        image: "https://i.postimg.cc/BnTc2sgC/e6b79d1a-fb72-4010-ade2-8c9a884aabe0.png", 
        details:"The Chevrolet Pickup from the Master Series era is a classic American workhorse from the late 1930s. It combined durability with art-deco styling.", 
      year: "1933",
      horsepower: "85",
      maxspeed: "113",
      fabriek: " Flint, USA",
      unique: "age",
      datum: "14-06-2023",
      },
  
        { name: "Subaru 360", 
          brand: "Subaru", 
          number: "392.016",
          liter: "0,365", 
          image: "https://i.postimg.cc/3WBqSphK/a071c345-da0c-4c6d-9250-4d1c6435b9be.png", 
          details:"The Subaru 360 was Japan’s first mass-produced car and marked the beginning of Subaru’s automotive history. It was nicknamed the “ladybug” for its round shape and tiny size." },
         
          { name: "Lamborghini Huracán Performante",
            liter: "5,2", 
            number: "1 800", 
            brand: "Lamborghini",
            image: "https://i.postimg.cc/Fd6yFqPZ/6ad47809-61d8-48a8-ae2a-c07c49d884cf.png", 
            details:"The Lamborghini Huracán Performante is a track-focused version of the Huracán, known for its aggressive design and incredible performance." },
  
            { name: "Mercedes-Benz EQE", 
              brand: "Mercedes-Benz",
              liter: "The motor is electric", 
              number: "3 076",
              image: "https://i.postimg.cc/mh8D9CRv/da8ff44a-32be-4235-bae7-bc5c0d45b0c9.png", 
              details:"The Mercedes-Benz EQE is a luxury electric sedan from the EQ lineup, offering advanced technology and elegant design." },
  
              { name: "Chevrolet Suburban",
                brand: "Chevrolet",
                liter: "5,3", 
                number: "10 million", 
                image: "https://i.postimg.cc/m1gFMGDM/67c49047-c98d-41d4-8aad-a24d15c7d88b.png", 
                details:"The Chevrolet Suburban is one of the longest-running nameplates in automotive history, known for its full-size versatility and space.", 
                year: "1935",
                horsepower: "355",
                maxspeed: "182",
                fabriek: " Flint, USA",
                unique: "horsepower and age",
                datum: "22-08-2024",
              },
  
                { name: "Chevrolet AK Series Pickup",
                  liter: "3,5", 
                  number: "428.000",
                  brand: "Chevrolet", 
                  image: "https://i.postimg.cc/G9t2kKKk/09600b1d-9e2d-44ea-9ea2-45d9df3571e5.png", 
                  details:"The Chevrolet AK Series was a line of light-duty trucks built in the 1940s, widely used during and after World War II.",
                  number: "428 000",
                  liter: "3,5",
                  year: "1941",
                  horsepower: "95",
                  maxspeed: "100-105",
                  fabriek: "Flint, USA",
                  unique: "age",
                  datum: "22-08-2024",
                },
  
                  { name: "Ford Mustang Convertible",
                    liter: "5,0",
                    number: "5,0More than 1,25 million", 
                    brand: "Ford",
                    image: "https://i.postimg.cc/PLtL0wsh/1aac1e0b-6616-4e06-9776-8ab07ba56a11.png", 
                    details:"The Ford Mustang Convertible is a classic American muscle car with a soft top for open-air driving fun." },
  
    { name: "Fiat 600", 
      brand: "Fiat",
      liter: "0,767", 
      number: "2.944.000", 
      image: "https://i.postimg.cc/F1zqbW6g/714818f4-ee24-4f44-8a60-7ba74f7cee93.png", 
      details:"The Fiat 600 is a tiny Italian city car, loved for its compact size and simplicity." },
  
      { name: "Ford Mustang Coupe", 
        liter: "5 million",
        number: "5,0", 
        brand: "Ford", 
        image: "https://i.postimg.cc/d7DdNCcX/b2dca309-0548-4917-b5c2-67b2433a975e.png", 
        details:"The Ford Mustang Coupe is a hardtop version of the iconic Mustang — one of the most influential muscle cars ever built." },
  
        { name: "Morgan Plus 4",
          liter: "2,0", 
          number: "4,584", 
          brand : "Morgan",
          image: "https://i.postimg.cc/2VgSN9MC/d0bfd90d-f206-4480-acda-62531b348cba.png", 
          details:"The Morgan Plus 4 is a handcrafted British roadster with retro looks and modern engineering." },
  
          { name: "Cadillac Sedan DeVille",
            liter: "7,7", 
            number: "More than 4 million", 
            brand: "Cadillac",
            image: "https://i.postimg.cc/tYHGp0DR/d7d5d979-bcd6-4b3e-bc38-80429e722f3b.png", 
            details:"The Cadillac Sedan DeVille is a full-size American luxury car known for its smooth ride, spacious interior, and bold presence. Blending classic elegance with powerful V8 performance, it defined upscale comfort for generations." },
  
            { name: "Ford Thunderbird",
              liter: "7,5",
               number: "More than 4,4 million",
               brand: "Ford",
               image: "https://i.postimg.cc/DSGgFZfm/25bfc576-12d0-40f7-880b-eaed30d1eec1.png", 
               details:"The Ford Thunderbird is a stylish American icon that blended performance with personal luxury. With its distinctive design and powerful engines, it captured the spirit of mid-century cruising." },
  
               { name: "Pontiac Firebird Trans Am",
                liter: "7,5",
                 number: "1,25 million", 
                 brand: "Pontiac",
                 image: "https://i.postimg.cc/2LrC23HJ/742d1d18-9001-4163-8f14-f32f3d94b96d.png", 
                 details:"The Pontiac Firebird Trans Am is a legendary American muscle car, famed for its aggressive styling and thrilling V8 performance. A symbol of 70s and 80s car culture, it delivered attitude, speed, and unmistakable road presence." },
  
                 { name: "Bentley 3 Litre", 
                  liter: "6,9",number: "1622",
                  brand: "Bentley", 
                  image: "https://i.postimg.cc/tnTQxnRN/3e1ed2fd-69a4-445a-bea3-0573db4a9b2e.png", 
                  details:"The Bentley 3 Litre is a vintage British sports car that established Bentley’s reputation for speed and endurance in the 1920s. Handcrafted and race-proven, it combined elegance with raw performance, winning Le Mans twice." },
  
                  { name: "LGOC B-Type Double-Decker Bus",
                    liter: "5,0", 
                    number: "More than 3.000",
                    brand: "LGOC",
                    image: "https://i.postimg.cc/XXC1Jgg7/a8207c2d-b901-4580-a394-375b4abb39dc.png", 
                    details:"The LGOC B-Type was one of the world’s first mass-produced double-decker buses, introduced in London in the early 1910s. With its open top and sturdy design, it became an iconic symbol of Edwardian transport — even serving in World War I." },
  { name: "Chevrolet Camaro", 
    liter: "Different liter capacities",
    number: "More than 6.2 million",
    brand: "Chevrolet",
    image: "https://i.postimg.cc/4nMdvVq0/61639437-5a3f-4d34-bb6b-2c87c1d33414.png", 
    details:"The Chevrolet Camaro is a classic American muscle car known for its bold design and thrilling performance. Born to rival the Mustang, it delivers power, attitude, and pure driving excitement.", 
      year: "2014",
      horsepower: "400",
      maxspeed: "296",
      fabriek: "Flint, USA",
      unique: "speed",
      datum: "20-09-2024",
  },
  
    { name: "Chevrolet C/K",
      liter: "7,4",
      number: "More than 22 million",
      brand: "Chevrolet", 
      image: "https://i.postimg.cc/m1LzFsnG/04162ea5-d2e0-4ada-a01d-93c29ab908a0.png", 
      details:"The Chevrolet C/K is a rugged line of full-size pickup trucks that became a staple of American work and lifestyle from the 1960s through the '90s. Known for their durability and timeless design, C/K trucks balanced utility with everyday comfort.", 
      year: "1960",
      horsepower: "160",
      maxspeed: "140",
      fabriek: "Flint, USA",
      unique: "",
      datum: "22-08-2024",
    },
   
      { name: "Chevrolet C/K 1500",
        liter: "6,2",
        number: "10,3 million", 
        brand: "Chevrolet",
        image: "https://i.postimg.cc/qNnxH29h/e5768c08-78ac-4020-8054-fcf03836511b.png", 
        details:"The Chevrolet C/K 1500 is a half-ton pickup truck celebrated for its reliability, versatility, and classic American styling. Whether on the job or off-road, it delivers dependable performance with a no-nonsense attitude.",
      year: "1960",
      horsepower: "160",
      maxspeed: "160",
      fabriek: "Flint, USA",
      unique: "",
      datum: "20-09-2024",
      },
  
        { name: "Chevrolet S-10",
          liter: "4,5",
          number: "6,75 million",
          brand: "Chevrolet", 
          image: "https://i.postimg.cc/HcY8RhPM/f897a607-7a31-4508-8527-c3b59f2107ae.png", 
          details:"The Chevrolet S-10 is a compact pickup truck that brought Chevy’s rugged capability to a smaller, more urban-friendly size. Known for its agility and practicality, it became a popular choice for drivers needing a versatile daily workhorse.", 
      year: "1982",
      horsepower: "120",
      maxspeed: "150",
      fabriek: " Flint, USA",
      unique: "",
      datum: "",
        },
  
          { name: "Ford Mustang Fastback",
            liter: "7,0",
            number: "512.586", 
            brand: "Ford",
            image: "https://i.postimg.cc/0b0R2Xtj/7b8cf21e-7dd3-46e2-9871-a958c2367649.png", 
            details:"The Ford Mustang Fastback is an iconic American muscle car combining sleek, aerodynamic styling with powerful performance. Celebrated for its aggressive look and thrilling drive, it embodies the spirit of freedom and speed." },
  
            { name: "Citroën 2CV",
              image: "https://i.postimg.cc/vT48QJnC/9ab5dd87-0ce2-4770-bd40-0d1add6029cc.jpg",
               liter: "2,2",
               number: "5,114,969",
               brand: "Citroën",
                details:"The Citroën 2CV is a minimalist French classic designed for practicality and simplicity. Known for its quirky design and exceptional fuel efficiency, it became a beloved symbol of post-war mobility and rural charm." },
  
                { name: "Chevrolet Corvette C3",
                  liter: "5,7",
                  number: "0,5 million",
                  brand: "Chevrolet",
                   image: "https://i.postimg.cc/S2cqLSG7/eef1ca2b-f62f-49db-b879-edc746140743.png", 
                   details:"The Chevrolet Corvette C3 is a bold and aggressive American sports car, instantly recognizable by its shark-inspired design. Combining striking style with powerful V8 engines, it defined high-performance driving through the 1970s.", 
                   number: "500 000",
      liter: "5,7",
      year: "1967",
      horsepower: "325",
      maxspeed: "215",
      fabriek: " Flint, USA",
      unique: "",
      datum: "14-05-2023",
                  },
  
                   { name: "Freightliner FLD Christmas", 
                    liter: "",
                    number: "14,6",
                    brand: "Freightliner",
                    image: "https://i.postimg.cc/21dKxqp5/cc18ba64-6a99-49f8-a898-a0cea92d9531.png",
                     details:"The Freightliner FLD Christmas edition is a festive twist on the classic heavy-duty truck, blending rugged performance with seasonal flair. Known for its durability on long hauls, this special version adds a unique holiday spirit to the open road." },
  
                     { name: "Fiat 124 Sport Spider",
                      liter: "1,4",
                      number: "198.000",
                      brand: "Fiat", 
                      image: "https://i.postimg.cc/ygPsxFz4/d868d05e-de95-4e1e-9ce6-57483c06b927.png", 
                      details:"The Fiat 124 Sport Spider is a charming Italian roadster combining elegant design with spirited performance. Lightweight and agile, it offers an engaging driving experience wrapped in classic 1960s style." },
  
                      { name: "Citroën Méhari", 
                        liter: "2,5",
                        number: "144.953",
                        brand: "Citroën",
                        image: "https://i.postimg.cc/gXRLTtRy/06ffdc88-451e-4011-8141-ad44cddcbfc6.png",
                         details:"The Citroën Méhari is a quirky, lightweight French utility vehicle with a distinctive plastic body and off-road capability. Designed for fun and practicality, it became a symbol of carefree outdoor adventures and innovative simplicity." },
  
                         { name: "NG TC V8", 
                          liter: "3,5",
                          number: "10",
                          brand: "NG",
                          image: "https://i.postimg.cc/Bj7GrqBs/1a635d4b-203c-4f97-adde-b9eff86cc4f9.png",
                           details:"The NG TC V8 is a lightweight British kit car that perfectly blends vintage roadster styling with powerful Rover V8 engines. Known for its nimble handling and thrilling performance, it offers a pure and engaging driving experience for enthusiasts." },
  
                           { name: "Volkswagen Beetle",
                            liter: "3-4", 
                            number: "21.529.464",
                            brand: "Volkswagen", 
                            image: "https://i.postimg.cc/xqv018XK/3fce08b2-77f6-49b7-bedb-0b23ff3102f2.png", 
                            details:"The Volkswagen Beetle is an iconic compact car known for its distinctive rounded design and timeless appeal. Combining classic charm with modern engineering, it delivers a unique driving experience cherished worldwide." },
  
                            { name: "Jeep Cherokee XJ",
                              liter: "4,0", 
                              number: "2,88 million",
                              brand: "Jeep",
                              image: "https://i.postimg.cc/zLnnVffs/bd720ec0-7f9f-4642-a2a8-da9f57b93523.png", 
                              details:"This is a classic Jeep Cherokee XJ, known for its boxy design and off-road capabilities. It's a rugged and reliable SUV that became iconic in the late '90s." },
  
                              { name: "Porsche Taycan",
                                liter: "The motor is electric", 
                                number: "150.000",
                                brand: "Porsche",
                                image: "https://i.postimg.cc/w74KGq9Y/6821ad81-9023-4780-a7da-f0ec3d0a557f.png", 
                                details:"The Porsche Taycan is a high-performance electric car that combines luxury with cutting-edge technology. Its sleek design and powerful acceleration make it one of the most exciting EVs on the road today.",
                                year: "2019",
                                horsepower: "326-420",
                                maxspeed: "250 km/hour",
                                fabriek: "Stuggart, Germany",
                                unique: "Car looks good and beautiful",
                                datum: "07-07-2025"
                              },
                                { name: 
                                  "Opel Blitz",
                                  liter: "2,1-2,5",
                                  number: "442.312", 
                                  brand: "Opel",
                                  image: "https://i.postimg.cc/jdTR2nCQ/20220728-111551.jpg", 
                                  details:"This is an Opel Blitz from the 1930s, a legendary German pickup truck with wooden side panels. It was widely used for transportation in both civilian and military sectors." },
  
                                  { name: "American LaFrance",
                                    liter: "14,5",
                                     number: "10.000-12.000",
                                     brand:"LaFrance",
                                     image: "https://i.postimg.cc/WbmfnXjC/20220728-120245.jpg",
                                      details:"This is an early 20th-century American LaFrance fire truck, famous for its iconic red design and impressive equipment. It was used to fight fires in big cities and is now a symbol of historic firefighting technology." },
  
                                      { name: "Volvo Amazon Combi",
                                        liter: "1.6,1.8 or 2.0",
                                        number: "67 000", 
                                        brand: "Volvo",
                                        image: "https://i.postimg.cc/DwJ356TW/IMG-20250803-140311.jpg", 
                                        details:"The Volvo Amazon Combi is a classic Swedish estate car known for its timeless design, robust build, and enduring charm. Introduced in the 1960s, it combined practicality with elegant styling, making it a favorite among vintage car enthusiasts.",
                                         year: "1956",
                                         horsepower: "75",
                                         maxspeed: "145",
                                         fabriek: "Goteborg, Sweden",
                                         unique: "design",
                                         datum: "03-08-2025",
                                      },
  
                                        { name: "Mercedes-Benz W201",
                                          liter: "1,8",
                                          number: "1,25",
                                          brand: "Mercedes-Benz",
                                           image: "https://i.postimg.cc/7YpwFdX1/IMG-20250803-160112.jpg",
                                            details:"The Mercedes-Benz W201, also known as the 190 series, marked a turning point for the brand with its compact dimensions and advanced engineering. Introduced in the 1980s, it combined understated luxury with innovative safety features, earning its place as a timeless icon." },
  
                                            { name: "Volvo 144",
                                              liter: "1,9",
                                              number: "443 000", 
                                              brand: "Volvo",
                                              image: "https://i.postimg.cc/SxfQcV7W/IMG-20250803-140427.jpg",
                                               details:"The Fiat 850 Sport Coupe is a classic Italian gem known for its sleek design and nimble performance. With its distinctive round headlights and spirited engine, it captured the hearts of car enthusiasts in the late 1960s.",
                                         year: "1966",
                                         horsepower: "100",
                                         maxspeed: "160",
                                         fabriek: "Goteborg, Sweden",
                                         unique: "design",
                                         datum: "03-08-2025",
                                              },
  
                                               { name: "Mercedes-Benz TN",
                                                liter: "",
                                                number: "", 
                                                brand: "Mercedes-Benz",
                                                image: "https://i.postimg.cc/WzZ8yd5P/IMG-20250723-164206.jpg", 
                                                details:"The Mercedes-Benz TN, also known as the T1, was a versatile van series produced from 1977 to 1995, widely used for transport, emergency services, and camper conversions. Its robust design and reliable diesel engines made it a favorite across Europe for both commercial and recreational use." },
  
                                                { name: "Mercedes-Benz SL",
                                                  liter: "",
                                                  number: "",
                                                  brand: "Mercedes-Benz",
                                                   image: "https://i.postimg.cc/W18Q112R/IMG-20250808-184820.jpg",
                                                    details:"The Mercedes-Benz SL is a legendary roadster that blends timeless elegance with cutting-edge performance. With its sleek design and powerful engine, it offers a luxurious driving experience that’s both thrilling and refined." },
  
  
{ name: "Porsche Panamera Custom", 
    liter: "",
    number: "",
    brand: "Porsche", 
    image: "https://i.postimg.cc/Rh0TG4kt/IMG-20250808-184641.jpg", 
    details:"The Porsche Panamera blends high-performance engineering with luxurious comfort, making it a standout in the world of premium sports sedans. With its sleek design and powerful engine options, it delivers an exhilarating driving experience without compromising everyday practicality.", 
    number: "about 300 000",
    liter: "3,2",
    year: "2009",
    horsepower: "310",
    maxspeed: "270",
    fabriek: "Stuggart, Germany",
    unique: "Speed",
    datum: "08-08-2025"
},
  { name: "Jaguar XJ", 
    liter: "",
    number: "",
    brand: "Jaguar",
    image: "https://i.postimg.cc/C1xDpJcT/IMG-20250723-170511.jpg",
     details:"The Jaguar XJ is a flagship luxury sedan that exudes sophistication and dynamic performance. With its sleek silhouette and refined interior, it offers a driving experience that’s both elegant and exhilarating." },
  
     { name: "Chevrolet Corvette C1",
       brand: "Chevrolet",
       image: "https://i.postimg.cc/brQ2QMJn/cb5f2eea-7d73-4ec0-8390-f75c6aa14595.jpg",
        details:"The Chevrolet Corvette C1 is an American classic that launched a legacy of high-performance sports cars. With its iconic curves and vintage charm, it captures the spirit of 1950s automotive innovation and style.",
        number: "69 015",
      liter: "4,5",
      year: "1953",
      horsepower: "200",
      maxspeed: "200",
      fabriek: " Flint, USA",
      unique: "age and design",
      datum: "09-08-2025",
      },
  
        { name: "BMW Z4 cabriolet",
          liter: "2,0-3,0",
          number: "",
           brand: "BMW",
           image: "https://i.postimg.cc/V6PfjNb7/d0f88d24-e34d-43fe-89cb-345b46d3d1c2.jpg",
            details:"The BMW Z4 is a stylish convertible that delivers precision handling and open-air excitement. With its sleek design and athletic stance, it’s built for drivers who crave both luxury and performance." },
  
  { name: "Fiat Ducato Turbo D camper",
    liter: "",
    number: "", 
    brand: "Fiat",
    image: "https://i.postimg.cc/028m1wsx/274d3117-1a9d-40a2-978c-3bc5aca557d5.jpg",
     details:"The Fiat Ducato Turbo D camper is a reliable travel companion built for long journeys and outdoor exploration. With its spacious interior and durable design, it offers the freedom to roam without sacrificing comfort." },
  
     { name: "Jaguar X-Type",
       liter: "",
       number: "",
       brand: "Jaguar",
       image: "https://i.postimg.cc/vZf92Nz6/IMG-20250813-155153-6016.jpg",
        details:"The Jaguar X-Type is a compact executive car produced between 2001 and 2009, designed to bring Jaguar’s luxury and style to a smaller, more affordable segment. Available as a sedan and later as an estate, it offered refined interiors, smooth performance, and all-wheel-drive options, while retaining the brand’s signature elegance." },
  
        { name: "Chrysler PT Cruiser Cabrios",
          liter: "", 
          number: "",
          brand: "Chrysler",
          image: "https://i.postimg.cc/XYfGkyjf/IMG-20250813-154923.jpg", 
          details:"The Chrysler PT Cruiser Cabrio is a convertible version of the iconic PT Cruiser, blending a distinctive retro style with the joy of open-top driving. Produced from 2005 to 2008, it offered seating for four, a practical folding soft top, and a choice of engines, making it a unique option in the small convertible market. Its bold design and unusual shape make it a recognizable classic even today." },
  
          { name: "Chevrolet Impala",
            liter: "5,4",
             number: "More than 1,1 million",
             brand: "Chevrolet",
             image: "https://i.postimg.cc/ZKk6PmPh/IMG-20250813-154656.jpg",
              details:"The Chevrolet Impala is a full-size car known for its spacious interior, smooth ride, and classic American styling. Produced over multiple generations, it has offered a range of engines and trims, combining comfort, practicality, and a touch of elegance for everyday driving.",
      year: "1958",
      horsepower: "275",
      maxspeed: "200",
      fabriek: " Flint, USA",
      unique: "design and style",
      datum: "13-08-2025",
            },
  
              { name: "Toyota Corolla E30",
                liter: "",
                 number: "",
                 brand: "Toyota",
                 image: "https://i.postimg.cc/cLtqpQg3/IMG-20250813-154425-5467.jpg",
                  details:"The Toyota Corolla E30, produced from 1974 to 1981, marked the third generation of the iconic Corolla series. Known for its reliability, fuel efficiency, and simple design, it became a popular choice worldwide for drivers seeking an affordable and durable compact car." },
  
                  { name: "Chevrolet Corvette C7",
                    liter: "", 
                    number: "",
                    brand: "Chevrolet",
                    image: "https://i.postimg.cc/X7hmkpHY/IMG-20250813-144734.jpg",
                     details:"The Chevrolet Corvette C7, produced from 2014 to 2019, is a seventh-generation sports car that combines aggressive styling with high performance. Equipped with a powerful V8 engine, advanced handling technologies, and a refined interior, it delivers an exhilarating driving experience while maintaining the Corvette’s iconic legacy.",
                      number: "87 770",
                      liter: "6,2",
      year: "2013",
      horsepower: "460",
      maxspeed: "290",
      fabriek: " Flint, USA",
      unique: "design and speed",
      datum: "13-08-2025",
  
                    },
  
                     { name: "BMW i4 V50",
                      number: "",
                      liter: "",
                       brand: "BMW",
                       image: "https://i.postimg.cc/pTXsHHGS/IMG-20250813-144712.jpg",
                        details:"The BMW i4 M50 is a high-performance all-electric Gran Coupé that combines luxury, style, and cutting-edge technology. With dual electric motors producing 544 hp, it accelerates from 0 to 100 km/h in just 3.9 seconds, offering thrilling performance while maintaining an impressive electric range of up to 510 km (WLTP). Its sleek design, advanced handling, and sustainable powertrain make it a standout choice in the electric sports sedan market." },
  
                        {name: "Mercedes-Benz W114",
                          liter: "",
                          number: "",
                           brand: "Mercedes-Benz",
                            image: "https://i.postimg.cc/jddn4jWm/IMG-20250813-154706.jpg",
                             details: "The Mercedes-Benz W114, produced from 1968 to 1976, is a classic executive car known for its solid build quality and timeless design. Offered in sedan and coupe versions, it combined reliability, comfort, and elegant styling, making it a popular choice among professionals and car enthusiasts alike."},
                          
  {name: "Mercedes-Benz W116",
    liter: "",
    number: "", 
    brand: "Mercedes-Benz", 
    image: "https://i.postimg.cc/DwyYnnb4/ed109081-3183-48fb-a9da-5ba3178c9a5f.jpg", 
    details: "The Mercedes-Benz W116 was produced from 1972 to 1980 and was the first official S-Class model. It introduced advanced safety features like ABS and reinforced crumple zones. The car offered powerful engines, including the legendary 450 SEL 6.9 with hydropneumatic suspension. Its design was bold and elegant, matched by a luxurious interior. Today, the W116 is a classic symbol of Mercedes-Benz innovation and prestige."},
  {name: "Volvo 760",
    liter: "2,9",
    number: "290 000",
     brand: "Volvo",
      image: "https://i.postimg.cc/SRfDbvSG/310e6b6a-41ca-458c-a039-9c7337680deb.jpg",
        details: "The Volvo 760 was introduced in 1982 as a premium executive car, known for its boxy design and solid build quality. It featured rear-wheel drive and came with a range of engines, including V6 and turbocharged four-cylinder options. The 760 offered advanced safety features and a comfortable, well-equipped interior. A station wagon version was also available, popular for its practicality and durability. Today, the Volvo 760 is appreciated as a classic example of Scandinavian engineering and understated luxury.", 
                                         year: "1982",
                                         horsepower: "165",
                                         maxspeed: "200",
                                         fabriek: "Goteborg, Sweden",
                                         unique: "speed and age",
                                         datum: "25-08-2025",
      },
  
       {name: "Volkswagen Golf Mk2",
        liter: "",
        number: "",
         brand: "Volkswagen", 
         image: "https://i.postimg.cc/MKtdsNr6/f0ce9e91-a9c1-449e-8d04-1e6ceafb79f7.jpg",
          details: "The Volkswagen Golf Mk2 was produced from 1983 to 1992 as the second generation of the popular Golf series. It featured a larger body than its predecessor, offering improved interior space and comfort. The car came with a wide range of engines, including fuel-efficient diesels and sporty GTI versions. Known for its reliability and solid build, the Mk2 became a favorite across Europe and beyond. Today, it’s considered a classic, loved for its timeless design and practical performance."},
  
          {name: "Mercedes-Benz G-Klasse",
            liter: "",
            number: "",
             brand: "Mercedes-Benz",
              image: "https://i.postimg.cc/dQ7tqCnh/5a68500a-1de3-4e14-be7a-3491b2990bc0.jpg",
               details: "The Mercedes-Benz G-Class, also known as the G-Wagen, was originally developed in 1979 as a military vehicle. Its boxy design and exceptional off-road capabilities quickly made it popular among civilians. Over the years, it evolved into a luxury SUV, combining rugged performance with high-end comfort and technology. The G-Class is known for its powerful engines, including V8 and AMG variants, and its iconic, timeless shape. Today, it remains a symbol of prestige and durability, loved by adventurers and luxury enthusiasts alike."},
  
               {name: "Citroën CX",
                liter: "",
                number: "", 
                brand: "Citroën", 
                image: "https://i.postimg.cc/6qCk8Bym/b5babf44-91ea-428d-9e12-cfdb1dbd27dc.jpg", 
                details: "The Citroën CX was produced from 1974 to 1991 as a large executive car, succeeding the iconic Citroën DS. It featured a futuristic design with a low drag coefficient and a distinctive fastback shape. The CX was famous for its hydropneumatic self-leveling suspension, offering an exceptionally smooth ride. It came in various body styles, including sedan and estate, with a range of petrol and diesel engines. Voted European Car of the Year in 1975, the CX remains a symbol of French innovation and comfort."},
  
                {name: "Mercedes-Benz E-klasse Estate",
                  liter: "",
                  number: "",
                   brand: "Mercedes-Benz",
                    image: "https://i.postimg.cc/Hxwz5n9X/4fa4a312-ce54-4046-b3f7-29f8174c136a.jpg",
                     details: "The Mercedes-Benz E-Class Estate is a luxury station wagon that blends elegance with practicality. Known for its spacious interior and up to 1,830 liters of cargo capacity, it’s perfect for families and long journeys. The design features sleek lines, LED lighting, and a refined front grille that highlight its premium character. Inside, it offers high-quality materials, advanced infotainment, and the latest driver-assistance systems. Combining German engineering with timeless style, the E-Class Estate remains a top choice for those who want comfort without compromise."},
  
                     {name: "Volvo 240",
                      liter: "2,3",
                      number: "about 2,8 million",
                       brand: "Volvo",
                        image: "https://i.postimg.cc/SK8fFR53/3851929e-1e1f-45ff-96bb-c6dcb93b9075.jpg",
                         details: "The Volvo 240 was produced from 1974 to 1993 and became one of the brand’s most iconic models. Known for its boxy design and exceptional durability, it earned a reputation for safety and reliability. The car featured rear-wheel drive, solid engineering, and a range of engines including the famous “redblock” series. Available as a sedan and station wagon, it was popular with families, professionals, and even rally drivers. Today, the Volvo 240 is a beloved classic, often praised for its timeless style and legendary toughness.",
                                         year: "1974",
                                         horsepower: "109",
                                         maxspeed: "170",
                                         fabriek: "Goteborg, Sweden",
                                         unique: "",
                                         datum: "15-08-2025", },


  {name: "Opel Corsa",
    liter: "",
    number: "", 
    brand: "Opel",
     image: "https://i.postimg.cc/mZSfJS77/a174f811-b7d4-49be-9471-d89403409180.jpg", 
     details: "The Opel Corsa is a compact hatchback that blends efficiency, style, and practicality for everyday driving. Available in electric, hybrid, and petrol versions, it’s a versatile choice for city life and beyond."},
  
     {name: "Cadillac Eldorado",
      liter: "",
      number: "",
       brand: "Cadillac", 
       image: "https://i.postimg.cc/T20FC3X9/f29f7f2d-ccab-41df-b36b-2e1c2e18f4a1.jpg",
        details: "The Cadillac Eldorado is a legendary American luxury coupe produced from 1952 to 2002, known for its bold styling and powerful V8 engines. As a symbol of elegance and innovation, it defined personal luxury for generations of drivers."},
  
        {name: "BMW Alpina",
          liter: "",
          number: "",
           brand: "BMW",
            image: "https://i.postimg.cc/VkvJdvzH/6c002ef3-f90f-486a-b458-0c9de178e531.jpg",
             details: "BMW Alpina is a high-performance automotive brand that refines select BMW models with enhanced engines, luxurious interiors, and exclusive styling. Known for its precision engineering and limited production, Alpina offers a unique blend of comfort and speed for discerning drivers."},
  
             {name: "BMW 2002 tii",
              liter: "",number: "",
               brand: "BMW",
                image: "https://i.postimg.cc/Vv2Vn53B/ac685d90-c3cd-421f-9e54-9fba7b8bc777.jpg",
                 details: "The BMW 2002 tii is a legendary compact sports sedan from the 1970s, known for its mechanical fuel injection and precise handling. It helped establish BMW’s reputation for building affordable performance cars and remains a beloved classic among enthusiasts."},
  
                 {name: "BMW 323i",
                  liter: "",
                  number: "", 
                  brand: "BMW",
                   image: "https://i.postimg.cc/k4z0FjSb/d04c5680-d991-4262-97c9-9ddb76425883.jpg",
                    details: "The BMW 323i, especially in its classic E21 generation, offered a refined balance of power and elegance with its inline-six engine. As one of the top variants of the early 3 Series, it helped define BMW’s sporty sedan legacy for decades."},
  
                    {name: "BMW 2002",
                      liter: "",
                      number: "", 
                      brand: "BMW", 
                      image: "https://i.postimg.cc/yNWpQmsX/f2259b11-5113-4594-a3ea-11587f9feefd.jpg", 
                      
                      details: "The BMW 2002 is a classic compact sedan produced from 1968 to 1976, known for its sporty handling and timeless design. As a pioneer of the brand’s performance legacy, it laid the foundation for the iconic BMW 3 Series."},
  {name: "Land Rover Series II",
    liter: "",
    number: "", 
    brand: "Land Rover",
     image: "https://i.postimg.cc/LsrDxGy2/7e69a752-2688-423b-b60b-6ea82ad5cbd1.jpg",
      details: "The Land Rover Series II, produced from 1958 to 1971, is a rugged off-road icon known for its durability and simplicity. With its aluminum body and leaf-spring suspension, it became a trusted vehicle for farmers, explorers, and military forces around the world."},
  
];
      